name: flutter_application_example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  intl: ^0.18.0
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.11.0
  geolocator: ^9.0.2
  http: ^1.3.0
  latlong2: ^0.8.1
  url_launcher: ^6.3.1
  flutter_polyline_points: ^2.1.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo_app.svg
    - assets/images/google_icon.svg