name: flutter_application_example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  intl: ^0.18.0
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env